### PR TITLE
LPS-76978 Adds jsdocs to frontend-js-spa-web

### PR DESCRIPTION
**Pull request by brunobasto**
@jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mwilliams2014, could you please send this over to brian directly? Having the `@review` tags should be enough to get it through, and then you can process it at your own pace, but at least we make sure we have all comments properly tracked down from now on. Otherwise, this is going to conflict with other stuff coming in and is going to be hard to merge.

**Comment by jbalsas** [comment]
Actually, I just did it myself 😉 

https://github.com/brianchandotcom/liferay-portal/pull/54363

**Comment by jbalsas** [comment]
ci:close

**Comment by mwilliams2014** [comment]
ok @jbalsas . I thought you already had this merged in master. Usually it is before we review the API docs. I just search for @review in the master branch to see what needs reviewed. In the future, you can just send those changes to BChan and just cc me, or notify me however you prefer. Thanks for taking care of that. I'll continue my review and send it in bit by bit.

**Comment by jbalsas** [comment]
Yeah, that was the idea, but the PRs got crossed and just this one stayed, that's why I went ahead and sent it. Glad that was the right call! 😉

**Pull request closed without merging**
